import { EmptyState } from "@/components/EmptyState";
import { SectionHeader } from "@/components/SectionHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useFinanceContext } from "@/contexts/FinanceContext";
import { centsToInput, formatCurrency, toCents } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowDownLeft, ArrowUpRight, Building2, CreditCard, Landmark, Pencil, Plus, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const typeLabels: Record<string, string> = { checking: "Conta corrente", savings: "Poupança", credit_card: "Cartão de crédito", investment: "Investimentos", cash: "Dinheiro", other: "Outra carteira" };
const typeIcons: Record<string, typeof Landmark> = { checking: Landmark, savings: Building2, credit_card: CreditCard, investment: Landmark, cash: WalletCards, other: WalletCards };

export default function Accounts() {
  const { view, isTogether } = useFinanceContext();
  const accounts = trpc.finance.accounts.list.useQuery({ context: view });
  const activity = trpc.finance.transactions.list.useQuery({ context: view });
  return <div><SectionHeader eyebrow={isTogether ? "NÓS DOIS" : "PATRIMÔNIO"} title="Contas e carteiras" description={isTogether ? "Saldos consolidados das contas individuais de vocês." : "Organize seus saldos em um único lugar, sem perder a origem de cada recurso."} action={!isTogether ? <AccountDialog /> : undefined} />
    {accounts.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div className="h-56 animate-pulse rounded-2xl bg-white/[0.04]" key={index} />)}</div> : accounts.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{accounts.data.map(account => <AccountCard key={account.id} account={account} transactions={(activity.data ?? []).filter(row => row.transaction.accountId === account.id).slice(0, 3)} canManage={account.ownerId !== undefined && !isTogether} />)}</div> : <EmptyState icon={<WalletCards className="h-5 w-5" />} title="Sua estrutura financeira começa aqui" description="Adicione sua primeira conta, cartão ou carteira de investimento." action={!isTogether ? { label: "Adicionar conta", onClick: () => document.getElementById("new-account-trigger")?.click() } : undefined} />}</div>;
}

function AccountCard({ account, canManage, transactions }: { account: { id: number; name: string; type: string; balanceCents: number; openingBalanceCents: number; color: string; ownerId?: number }; canManage: boolean; transactions: Array<{ transaction: { id: number; type: "income" | "expense"; amountCents: number; description: string; occurredAt: Date }; owner: { name: string | null } }> }) {
  const Icon = typeIcons[account.type] ?? WalletCards;
  const utils = trpc.useUtils();
  const archive = trpc.finance.accounts.archive.useMutation({ onSuccess: async () => { await utils.finance.accounts.list.invalidate(); await utils.finance.dashboard.invalidate(); toast.success("Conta arquivada."); } });
  return <article className="relative overflow-hidden rounded-2xl border border-white/[0.08] bg-[#12131b] p-5 shadow-[0_18px_48px_rgba(0,0,0,.14)]"><div className="absolute inset-x-0 top-0 h-1" style={{ background: `linear-gradient(90deg, ${account.color}, transparent)` }} /><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl" style={{ background: `${account.color}20`, color: account.color }}><Icon className="h-5 w-5" /></span>{canManage && <div className="flex gap-1"><AccountDialog account={account} trigger={<Button size="icon" variant="ghost" className="h-8 w-8 text-slate-500 hover:bg-white/5 hover:text-white" aria-label={`Editar ${account.name}`}><Pencil className="h-3.5 w-3.5" /></Button>} /><Button disabled={archive.isPending} onClick={() => archive.mutate({ id: account.id })} size="icon" variant="ghost" className="h-8 w-8 text-slate-600 hover:bg-rose-400/10 hover:text-rose-300" aria-label={`Arquivar ${account.name}`}><Archive className="h-3.5 w-3.5" /></Button></div>}</div><p className="mt-7 text-sm font-medium text-slate-300">{account.name}</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em] text-white">{formatCurrency(account.balanceCents)}</p><div className="mt-7 flex items-center justify-between border-t border-white/[0.07] pt-3"><span className="text-xs text-slate-500">{typeLabels[account.type]}</span><span className="text-xs text-slate-600">Saldo inicial: {formatCurrency(account.openingBalanceCents)}</span></div><div className="mt-4 border-t border-white/[0.06] pt-3"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-600">Movimentações recentes</p>{transactions.length ? <div className="space-y-2">{transactions.map(row => <div key={row.transaction.id} className="flex items-center gap-2 text-xs"><span className={`grid h-5 w-5 place-items-center rounded-md ${row.transaction.type === "income" ? "bg-emerald-400/10 text-emerald-300" : "bg-rose-400/10 text-rose-300"}`}>{row.transaction.type === "income" ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownLeft className="h-3 w-3" />}</span><span className="min-w-0 flex-1 truncate text-slate-400">{row.transaction.description}</span><span className={row.transaction.type === "income" ? "text-emerald-300" : "text-slate-200"}>{row.transaction.type === "income" ? "+" : "−"}{formatCurrency(row.transaction.amountCents)}</span></div>)}</div> : <p className="text-xs text-slate-600">Nenhuma movimentação nesta conta.</p>}</div></article>;
}

function AccountDialog({ account, trigger }: { account?: { id: number; name: string; type: string; openingBalanceCents: number; color: string }; trigger?: React.ReactNode }) {
  const [open, setOpen] = useState(false); const utils = trpc.useUtils();
  const create = trpc.finance.accounts.create.useMutation({ onSuccess: async () => { await utils.finance.accounts.list.invalidate(); await utils.finance.dashboard.invalidate(); toast.success("Conta adicionada."); setOpen(false); } });
  const update = trpc.finance.accounts.update.useMutation({ onSuccess: async () => { await utils.finance.accounts.list.invalidate(); await utils.finance.dashboard.invalidate(); toast.success("Conta atualizada."); setOpen(false); } });
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const common = { name: String(form.get("name")).trim(), institution: String(form.get("institution")).trim() || undefined, openingBalanceCents: toCents(String(form.get("openingBalance"))), color: String(form.get("color")) }; if (!common.name) return; if (account) update.mutate({ id: account.id, ...common }); else create.mutate({ ...common, type: String(form.get("type")) as "checking" | "savings" | "credit_card" | "investment" | "cash" | "other" }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{trigger ?? <Button id="new-account-trigger" className="h-10 rounded-xl bg-violet-500 px-4 text-white hover:bg-violet-400"><Plus className="mr-2 h-4 w-4" />Nova conta</Button>}</DialogTrigger><DialogContent className="border-white/10 bg-[#151620] text-slate-100 sm:max-w-md"><DialogHeader><DialogTitle>{account ? "Editar conta" : "Adicionar conta"}</DialogTitle></DialogHeader><form onSubmit={save} className="mt-3 space-y-4"><label className="grid gap-2 text-xs font-medium text-slate-300">Nome da conta<input name="name" defaultValue={account?.name} className="atlas-input" placeholder="Ex.: Nubank" required /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Instituição<input name="institution" className="atlas-input" placeholder="Opcional" /></label>{!account && <label className="grid gap-2 text-xs font-medium text-slate-300">Tipo<select name="type" className="atlas-input"><option value="checking">Conta corrente</option><option value="savings">Poupança</option><option value="credit_card">Cartão de crédito</option><option value="investment">Investimentos</option><option value="cash">Dinheiro</option><option value="other">Outra carteira</option></select></label>}<div className="grid grid-cols-[1fr_auto] gap-3"><label className="grid gap-2 text-xs font-medium text-slate-300">Saldo inicial<input name="openingBalance" defaultValue={account ? centsToInput(account.openingBalanceCents) : "0,00"} className="atlas-input" inputMode="decimal" /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Cor<input name="color" type="color" defaultValue={account?.color ?? "#8B5CF6"} className="h-10 w-12 rounded-lg border border-white/10 bg-transparent p-1" /></label></div>{(create.error || update.error) && <p className="text-sm text-rose-300">{create.error?.message ?? update.error?.message}</p>}<div className="flex justify-end gap-3 pt-3"><Button type="button" variant="ghost" onClick={() => setOpen(false)} className="text-slate-400 hover:text-white">Cancelar</Button><Button disabled={create.isPending || update.isPending} type="submit" className="rounded-xl bg-violet-500 text-white hover:bg-violet-400">{create.isPending || update.isPending ? "Salvando..." : "Salvar"}</Button></div></form></DialogContent></Dialog>;
}
