import { EmptyState } from "@/components/EmptyState";
import { SectionHeader } from "@/components/SectionHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { currentMonthKey, formatCurrency, formatMonth, toCents } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Plus, ShieldAlert, Target } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

export default function Budgets() {
  const monthKey = currentMonthKey();
  const budgets = trpc.finance.budgets.list.useQuery({ monthKey });
  const categories = trpc.finance.categories.list.useQuery({ context: "individual" });
  const transactions = trpc.finance.transactions.list.useQuery({ context: "individual" });
  const spendingByCategory = useMemo(() => {
    const result = new Map<number, number>();
    (transactions.data ?? []).filter(row => row.transaction.type === "expense" && new Date(row.transaction.occurredAt).toISOString().slice(0, 7) === monthKey && row.transaction.categoryId).forEach(row => result.set(row.transaction.categoryId!, (result.get(row.transaction.categoryId!) ?? 0) + row.transaction.amountCents));
    return result;
  }, [transactions.data, monthKey]);
  const totalLimit = (budgets.data ?? []).reduce((total, item) => total + item.budget.limitCents, 0);
  const totalSpent = (budgets.data ?? []).reduce((total, item) => total + (spendingByCategory.get(item.budget.categoryId) ?? 0), 0);
  return <div><SectionHeader eyebrow="PLANEJAMENTO" title="Orçamento mensal" description={`Defina limites por categoria e acompanhe seus gastos de ${formatMonth(monthKey)} em tempo real.`} action={<BudgetDialog categories={(categories.data ?? []).filter(category => category.kind === "expense")} monthKey={monthKey} />} />
    <div className="mb-5 grid gap-4 md:grid-cols-3"><article className="atlas-panel p-5"><p className="text-xs uppercase tracking-[.13em] text-slate-500">Planejado</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em] text-white">{formatCurrency(totalLimit)}</p></article><article className="atlas-panel p-5"><p className="text-xs uppercase tracking-[.13em] text-slate-500">Utilizado</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em] text-white">{formatCurrency(totalSpent)}</p></article><article className="atlas-panel p-5"><p className="text-xs uppercase tracking-[.13em] text-slate-500">Disponível</p><p className={`mt-3 text-2xl font-semibold tracking-[-.04em] ${totalLimit - totalSpent < 0 ? "text-rose-300" : "text-emerald-300"}`}>{formatCurrency(totalLimit - totalSpent)}</p></article></div>
    {(budgets.data ?? []).length ? <div className="grid gap-4 xl:grid-cols-2">{budgets.data?.map(item => { const spent = spendingByCategory.get(item.budget.categoryId) ?? 0; const percent = Math.round(spent / item.budget.limitCents * 100); const alert = percent >= item.budget.alertThreshold; return <article key={item.budget.id} className="atlas-panel p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="h-3 w-3 rounded-full" style={{ background: item.category.color }} /><div><p className="font-medium text-slate-200">{item.category.name}</p><p className="mt-1 text-xs text-slate-500">{formatCurrency(spent)} de {formatCurrency(item.budget.limitCents)}</p></div></div>{alert && <span className={`inline-flex items-center gap-1 rounded-lg px-2 py-1 text-[11px] font-medium ${percent >= 100 ? "bg-rose-400/10 text-rose-300" : "bg-amber-400/10 text-amber-300"}`}>{percent >= 100 ? <ShieldAlert className="h-3.5 w-3.5" /> : <AlertTriangle className="h-3.5 w-3.5" />}{percent >= 100 ? "Limite excedido" : "Atenção"}</span>}</div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className={`h-full rounded-full transition-all ${percent >= 100 ? "bg-rose-400" : percent >= item.budget.alertThreshold ? "bg-amber-400" : "bg-violet-400"}`} style={{ width: `${Math.min(percent, 100)}%` }} /></div><div className="mt-3 flex justify-between text-xs"><span className={alert ? "text-amber-300" : "text-slate-500"}>{percent}% utilizado</span><span className="text-slate-500">Restam {formatCurrency(Math.max(item.budget.limitCents - spent, 0))}</span></div></article>; })}</div> : <EmptyState icon={<Target className="h-5 w-5" />} title="Sem limites definidos neste mês" description="Crie um orçamento para acompanhar seus gastos por categoria e receber alertas visuais." action={{ label: "Criar orçamento", onClick: () => document.getElementById("new-budget-trigger")?.click() }} />}
  </div>;
}

function BudgetDialog({ categories, monthKey }: { categories: { id: number; name: string }[]; monthKey: string }) {
  const [open, setOpen] = useState(false); const utils = trpc.useUtils();
  const upsert = trpc.finance.budgets.upsert.useMutation({ onSuccess: async () => { await utils.finance.budgets.list.invalidate(); toast.success("Orçamento salvo."); setOpen(false); } });
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const categoryId = Number(form.get("categoryId")); const limitCents = toCents(String(form.get("limit"))); if (!categoryId || !limitCents) { toast.error("Escolha uma categoria e um limite válido."); return; } upsert.mutate({ categoryId, monthKey, limitCents, alertThreshold: Number(form.get("threshold")) }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button id="new-budget-trigger" className="h-10 rounded-xl bg-violet-500 px-4 text-white hover:bg-violet-400"><Plus className="mr-2 h-4 w-4" />Novo orçamento</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#151620] text-slate-100 sm:max-w-sm"><DialogHeader><DialogTitle>Limite para {formatMonth(monthKey)}</DialogTitle></DialogHeader><form onSubmit={save} className="mt-3 space-y-4"><label className="grid gap-2 text-xs font-medium text-slate-300">Categoria<select name="categoryId" className="atlas-input" defaultValue=""> <option value="" disabled>Selecione uma categoria</option>{categories.map(category => <option className="bg-[#151620]" key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="grid gap-2 text-xs font-medium text-slate-300">Limite mensal<input name="limit" className="atlas-input" inputMode="decimal" placeholder="0,00" /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Avisar ao atingir<select name="threshold" className="atlas-input" defaultValue="80"><option value="70">70%</option><option value="80">80%</option><option value="90">90%</option></select></label>{upsert.error && <p className="text-sm text-rose-300">{upsert.error.message}</p>}<div className="flex justify-end gap-3 pt-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)} className="text-slate-400 hover:text-white">Cancelar</Button><Button disabled={upsert.isPending} type="submit" className="rounded-xl bg-violet-500 text-white hover:bg-violet-400">Salvar limite</Button></div></form></DialogContent></Dialog>;
}
