import { EmptyState } from "@/components/EmptyState";
import { SectionHeader } from "@/components/SectionHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useFinanceContext } from "@/contexts/FinanceContext";
import { formatCurrency, formatDate, toCents } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Goal as GoalIcon, Plus, TrendingUp } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Goals() {
  const { view, isTogether } = useFinanceContext();
  const goals = trpc.finance.goals.list.useQuery({ context: view });
  if (goals.error) return <EmptyState icon={<GoalIcon className="h-5 w-5" />} title="A visão conjunta ainda não está disponível" description={goals.error.message} />;
  return <div><SectionHeader eyebrow={isTogether ? "NÓS DOIS" : "FUTURO"} title="Metas financeiras" description={isTogether ? "Metas individuais em uma visão consolidada para acompanhar o futuro do casal." : "Transforme intenções em planos com prazo, valor-alvo e histórico de evolução."} action={!isTogether ? <GoalDialog /> : undefined} />
    {goals.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-56 animate-pulse rounded-2xl bg-white/[0.04]" />)}</div> : goals.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{goals.data.map(goal => <GoalCard key={goal.id} goal={goal} canContribute={!isTogether} />)}</div> : <EmptyState icon={<GoalIcon className="h-5 w-5" />} title={isTogether ? "Ainda não há metas no espaço compartilhado" : "Comece por um objetivo que importa"} description={isTogether ? "As metas individuais aparecerão aqui assim que forem criadas em cada perfil." : "Crie uma meta, defina um prazo e acompanhe cada contribuição rumo ao seu plano."} action={!isTogether ? { label: "Criar meta", onClick: () => document.getElementById("new-goal-trigger")?.click() } : undefined} />}</div>;
}

function GoalCard({ goal, canContribute }: { goal: { id: number; name: string; targetCents: number; targetDate: Date | null; color: string; contributions: { amountCents: number; contributedAt: Date }[] }; canContribute: boolean }) {
  const progressCents = goal.contributions.reduce((total, contribution) => total + contribution.amountCents, 0); const progress = Math.min(100, Math.round(progressCents / goal.targetCents * 100));
  return <article className="relative overflow-hidden rounded-2xl border border-white/[0.08] bg-[#12131b] p-5"><div className="absolute inset-x-0 top-0 h-1" style={{ background: `linear-gradient(90deg, ${goal.color}, transparent)` }} /><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl" style={{ background: `${goal.color}20`, color: goal.color }}><GoalIcon className="h-5 w-5" /></span><span className="rounded-lg bg-white/[0.05] px-2.5 py-1 text-xs font-medium text-slate-400">{progress}%</span></div><p className="mt-6 font-medium text-slate-200">{goal.name}</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em] text-white">{formatCurrency(progressCents)}</p><p className="mt-1 text-xs text-slate-500">de {formatCurrency(goal.targetCents)}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full" style={{ width: `${progress}%`, background: goal.color }} /></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span className="flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" />{goal.targetDate ? `Até ${formatDate(goal.targetDate)}` : "Sem prazo"}</span><span>{goal.contributions.length} contrib.</span></div>{canContribute && <div className="mt-5"><ContributionDialog goalId={goal.id} /></div>}</article>;
}

function GoalDialog() {
  const [open, setOpen] = useState(false); const utils = trpc.useUtils();
  const create = trpc.finance.goals.create.useMutation({ onSuccess: async () => { await utils.finance.goals.list.invalidate(); toast.success("Meta criada."); setOpen(false); } });
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const targetCents = toCents(String(form.get("target"))); if (!targetCents) { toast.error("Informe um valor-alvo válido."); return; } create.mutate({ name: String(form.get("name")).trim(), targetCents, targetDate: form.get("date") ? new Date(`${String(form.get("date"))}T12:00:00`) : null, color: String(form.get("color")) }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button id="new-goal-trigger" className="h-10 rounded-xl bg-violet-500 px-4 text-white hover:bg-violet-400"><Plus className="mr-2 h-4 w-4" />Nova meta</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#151620] text-slate-100 sm:max-w-sm"><DialogHeader><DialogTitle>Criar meta financeira</DialogTitle></DialogHeader><form onSubmit={save} className="mt-3 space-y-4"><label className="grid gap-2 text-xs font-medium text-slate-300">Nome<input name="name" className="atlas-input" placeholder="Ex.: Reserva de segurança" required /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Valor-alvo<input name="target" className="atlas-input" inputMode="decimal" placeholder="0,00" required /></label><div className="grid grid-cols-[1fr_auto] gap-3"><label className="grid gap-2 text-xs font-medium text-slate-300">Prazo<input name="date" type="date" className="atlas-input [color-scheme:dark]" /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Cor<input name="color" type="color" defaultValue="#A78BFA" className="h-10 w-12 rounded-lg border border-white/10 bg-transparent p-1" /></label></div>{create.error && <p className="text-sm text-rose-300">{create.error.message}</p>}<div className="flex justify-end gap-3 pt-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)} className="text-slate-400 hover:text-white">Cancelar</Button><Button disabled={create.isPending} type="submit" className="rounded-xl bg-violet-500 text-white hover:bg-violet-400">Criar meta</Button></div></form></DialogContent></Dialog>;
}

function ContributionDialog({ goalId }: { goalId: number }) {
  const [open, setOpen] = useState(false); const utils = trpc.useUtils();
  const contribute = trpc.finance.goals.contribute.useMutation({ onSuccess: async () => { await utils.finance.goals.list.invalidate(); toast.success("Contribuição registrada."); setOpen(false); } });
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const amountCents = toCents(String(form.get("amount"))); if (!amountCents) { toast.error("Informe um valor válido."); return; } contribute.mutate({ goalId, amountCents, note: String(form.get("note")).trim() || undefined }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="h-9 w-full rounded-xl border-white/10 bg-white/[0.025] text-xs text-violet-200 hover:bg-violet-400/10 hover:text-violet-100"><TrendingUp className="mr-2 h-3.5 w-3.5" />Adicionar contribuição</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#151620] text-slate-100 sm:max-w-sm"><DialogHeader><DialogTitle>Nova contribuição</DialogTitle></DialogHeader><form onSubmit={save} className="mt-3 space-y-4"><label className="grid gap-2 text-xs font-medium text-slate-300">Valor<input name="amount" className="atlas-input" inputMode="decimal" placeholder="0,00" /></label><label className="grid gap-2 text-xs font-medium text-slate-300">Observação<input name="note" className="atlas-input" placeholder="Opcional" /></label><div className="flex justify-end gap-3 pt-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)} className="text-slate-400 hover:text-white">Cancelar</Button><Button disabled={contribute.isPending} type="submit" className="rounded-xl bg-violet-500 text-white hover:bg-violet-400">Adicionar</Button></div></form></DialogContent></Dialog>;
}
