import { EmptyState } from "@/components/EmptyState";
import { SectionHeader } from "@/components/SectionHeader";
import { useFinanceContext } from "@/contexts/FinanceContext";
import { formatCurrency, formatMonth } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, TrendingUp } from "lucide-react";

const tooltipStyle = { background: "#1a1b26", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#e2e8f0", fontSize: 12 };
export default function Reports() {
  const { view, isTogether } = useFinanceContext(); const report = trpc.finance.reports.useQuery({ context: view });
  if (report.isLoading) return <div className="grid gap-5 xl:grid-cols-2"><div className="h-80 animate-pulse rounded-2xl bg-white/[0.04]" /><div className="h-80 animate-pulse rounded-2xl bg-white/[0.04]" /></div>;
  if (report.error) return <EmptyState icon={<BarChart3 className="h-5 w-5" />} title="A visão conjunta ainda não está disponível" description={report.error.message} />;
  const monthly = (report.data?.monthly ?? []).map(item => ({ ...item, label: formatMonth(item.key).slice(0, 3), receitas: item.incomeCents / 100, despesas: item.expenseCents / 100, patrimonio: item.netWorthCents / 100 }));
  const currentPeriod = monthly.at(-1); const previousPeriod = monthly.at(-2); const cashflowChange = currentPeriod && previousPeriod ? (currentPeriod.receitas - currentPeriod.despesas) - (previousPeriod.receitas - previousPeriod.despesas) : null;
  return <div><SectionHeader eyebrow={isTogether ? "NÓS DOIS" : "INTELIGÊNCIA FINANCEIRA"} title="Relatórios" description="Evolução patrimonial, comportamento de gastos e fluxo de caixa em uma leitura objetiva." />
    <div className="grid gap-5 xl:grid-cols-2"><ChartPanel title="Evolução patrimonial" description="Posição consolidada no fim de cada mês"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly} margin={{ top: 10, right: 5, left: -18, bottom: 0 }}><defs><linearGradient id="worthGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a78bfa" stopOpacity={.3} /><stop offset="100%" stopColor="#a78bfa" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 11 }} tickFormatter={(value: number) => `R$${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [formatCurrency(value * 100), "Patrimônio"]} /><Area type="monotone" dataKey="patrimonio" stroke="#a78bfa" strokeWidth={2.5} fill="url(#worthGradient)" /></AreaChart></ResponsiveContainer></ChartPanel>
      <ChartPanel title="Fluxo de caixa mensal" description="Entradas e saídas dos últimos seis meses"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly} margin={{ top: 10, right: 5, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 11 }} tickFormatter={(value: number) => `R$${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [formatCurrency(value * 100), ""]} /><Bar dataKey="receitas" fill="#34d399" radius={[5, 5, 0, 0]} /><Bar dataKey="despesas" fill="#fb7185" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel>
      <ChartPanel title="Despesas por categoria" description="Como o orçamento foi distribuído neste mês"><div className="flex h-full items-center">{report.data?.categoryTotals.length ? <><div className="h-full w-[56%]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={report.data.categoryTotals} dataKey="valueCents" nameKey="name" innerRadius={63} outerRadius={92} paddingAngle={3} stroke="none">{report.data.categoryTotals.map((item, index) => <Cell key={index} fill={item.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => formatCurrency(value)} /></PieChart></ResponsiveContainer></div><div className="w-[44%] space-y-3">{report.data.categoryTotals.slice(0, 5).map(item => <div className="flex items-center gap-2" key={item.name}><span className="h-2 w-2 rounded-full" style={{ background: item.color }} /><span className="min-w-0 flex-1 truncate text-xs text-slate-400">{item.name}</span><span className="text-xs font-medium text-slate-200">{formatCurrency(item.valueCents, true)}</span></div>)}</div></> : <div className="w-full text-center text-sm text-slate-600">Sem despesas categorizadas neste mês.</div>}</div></ChartPanel>
      <section className="atlas-panel p-6"><p className="text-sm font-semibold text-white">Leitura do período</p><p className="mt-1 text-xs text-slate-500">Síntese operacional dos últimos seis meses</p><div className="mt-6 space-y-4">{monthly.length ? <><Insight label="Resultado médio mensal" value={formatCurrency(Math.round(monthly.reduce((sum, item) => sum + item.receitas - item.despesas, 0) / monthly.length * 100))} icon={<TrendingUp className="h-4 w-4" />} /><Insight label="Maior volume de despesas" value={formatCurrency(Math.max(...monthly.map(item => item.despesas)) * 100)} icon={<BarChart3 className="h-4 w-4" />} /><Insight label="Patrimônio atual" value={formatCurrency((monthly.at(-1)?.patrimonio ?? 0) * 100)} icon={<TrendingUp className="h-4 w-4" />} /></> : <p className="text-sm text-slate-500">Registre movimentos para gerar seus primeiros comparativos.</p>}</div></section>
      <section className="atlas-panel p-6 xl:col-span-2"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-sm font-semibold text-white">Comparativo entre períodos</p><p className="mt-1 text-xs text-slate-500">Leitura do último mês em relação ao período imediatamente anterior.</p></div>{currentPeriod && previousPeriod ? <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${cashflowChange !== null && cashflowChange >= 0 ? "bg-emerald-400/10 text-emerald-300" : "bg-rose-400/10 text-rose-300"}`}>{cashflowChange !== null && cashflowChange >= 0 ? "+" : ""}{formatCurrency((cashflowChange ?? 0) * 100)} no fluxo</span> : null}</div>{currentPeriod && previousPeriod ? <div className="mt-6 grid gap-3 sm:grid-cols-3"><CompareMetric label="Receitas" current={currentPeriod.receitas} previous={previousPeriod.receitas} /><CompareMetric label="Despesas" current={currentPeriod.despesas} previous={previousPeriod.despesas} invert /><CompareMetric label="Patrimônio" current={currentPeriod.patrimonio} previous={previousPeriod.patrimonio} /></div> : <p className="mt-6 text-sm text-slate-500">Quando houver dados em dois meses diferentes, a comparação aparecerá aqui.</p>}</section>
    </div>
  </div>;
}
function ChartPanel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="atlas-panel p-5 sm:p-6"><p className="text-sm font-semibold text-white">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p><div className="mt-5 h-[280px]">{children}</div></section>; }
function Insight({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3.5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-violet-400/10 text-violet-300">{icon}</span><span className="flex-1 text-sm text-slate-400">{label}</span><span className="text-sm font-semibold text-white">{value}</span></div>; }
function CompareMetric({ label, current, previous, invert = false }: { label: string; current: number; previous: number; invert?: boolean }) { const delta = current - previous; const positive = invert ? delta <= 0 : delta >= 0; return <div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold tracking-[-.03em] text-white">{formatCurrency(current * 100)}</p><p className={`mt-1 text-xs font-medium ${positive ? "text-emerald-300" : "text-rose-300"}`}>{delta >= 0 ? "+" : ""}{formatCurrency(delta * 100)} vs. mês anterior</p></div>; }
