import { EmptyState } from "@/components/EmptyState";
import { MetricCard } from "@/components/MetricCard";
import { SectionHeader } from "@/components/SectionHeader";
import { Button } from "@/components/ui/button";
import { useFinanceContext } from "@/contexts/FinanceContext";
import { formatCurrency } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Check, Copy, HeartHandshake, Landmark, Link2, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function Together() {
  const { setView } = useFinanceContext(); const [_, setLocation] = useLocation();
  const household = trpc.finance.household.status.useQuery(); const dashboard = trpc.finance.dashboard.useQuery({ context: "together" }, { retry: false, enabled: Boolean(household.data?.complete) });
  useEffect(() => { setView(household.data?.complete ? "together" : "individual"); }, [setView, household.data?.complete]);
  if (household.isLoading) return <div className="h-72 animate-pulse rounded-2xl bg-white/[0.04]" />;
  if (!household.data?.complete) return <PairingPanel household={household.data?.household ?? null} inviteCode={household.data?.household?.inviteCode ?? null} />;
  const summary = dashboard.data?.summary;
  return <div><SectionHeader eyebrow="NÓS DOIS" title="Uma visão para os planos compartilhados." description="A consolidação soma os dados dos dois perfis sem alterar a origem de nenhuma transação." action={<Button onClick={() => setLocation("/relatorios")} className="h-10 rounded-xl bg-violet-500 px-4 text-white hover:bg-violet-400">Ver relatórios do casal</Button>} /><div className="mb-5 flex flex-wrap items-center gap-2 rounded-2xl border border-emerald-400/15 bg-emerald-400/[0.06] px-4 py-3 text-sm text-emerald-100"><ShieldCheck className="h-4 w-4 text-emerald-300" />Conexão ativa entre {household.data.members.map(member => member.name || "Perfil").join(" e ")}. Cada lançamento continua vinculado ao seu autor.</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Patrimônio conjunto" valueCents={summary?.netWorthCents ?? 0} detail="posições consolidadas" trend={summary?.variationPercent} icon={<Landmark className="h-5 w-5" />} /><MetricCard label="Receitas do mês" valueCents={summary?.incomeCents ?? 0} detail="dos dois perfis" accent="emerald" icon={<Plus className="h-5 w-5" />} /><MetricCard label="Despesas do mês" valueCents={summary?.expenseCents ?? 0} detail="dos dois perfis" accent="rose" icon={<UsersRound className="h-5 w-5" />} /><MetricCard label="Resultado mensal" valueCents={summary?.cashflowCents ?? 0} detail="entradas menos saídas" accent="sky" icon={<HeartHandshake className="h-5 w-5" />} /></div><section className="atlas-panel mt-5 p-6"><p className="text-sm font-semibold text-white">Visão consolidada em tempo real</p><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">O saldo conjunto de <strong className="font-semibold text-slate-200">{formatCurrency(summary?.netWorthCents ?? 0)}</strong> é calculado a partir das contas e transações individuais de cada pessoa. Navegue por transações, contas e relatórios mantendo o modo <strong className="font-semibold text-violet-200">Nós dois</strong> ativo.</p></section></div>;
}

function PairingPanel({ household, inviteCode }: { household: { name: string; inviteCode: string } | null; inviteCode: string | null }) {
  const utils = trpc.useUtils(); const [name, setName] = useState(""); const [code, setCode] = useState("");
  const create = trpc.finance.household.create.useMutation({ onSuccess: async () => { await utils.finance.household.status.invalidate(); toast.success("Espaço Nós dois criado. Compartilhe o código com seu parceiro."); } });
  const join = trpc.finance.household.join.useMutation({ onSuccess: async () => { await utils.finance.household.status.invalidate(); toast.success("Vocês estão conectados. A visão conjunta está pronta."); } });
  const createSpace = (event: FormEvent) => { event.preventDefault(); if (name.trim()) create.mutate({ name: name.trim() }); };
  const joinSpace = (event: FormEvent) => { event.preventDefault(); if (code.trim()) join.mutate({ inviteCode: code.trim() }); };
  if (household && inviteCode) return <div><SectionHeader eyebrow="NÓS DOIS" title="Convide a outra pessoa para sua visão conjunta." description="O código abaixo cria uma ligação segura entre dois perfis. Dados individuais só são consolidados quando ambos entrarem nesse espaço." /><section className="mx-auto max-w-2xl rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/15 to-indigo-500/[0.04] p-6 sm:p-10"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-violet-400/15 text-violet-200"><Link2 className="h-6 w-6" /></div><h2 className="mt-6 text-2xl font-semibold tracking-[-.04em] text-white">{household.name}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Envie este código à pessoa que fará parte da sua visão financeira. O código aceita apenas um segundo perfil.</p><div className="mt-6 flex items-center justify-between gap-3 rounded-2xl border border-white/[0.1] bg-[#0c0d13]/70 p-4"><code className="truncate text-lg font-semibold tracking-[.16em] text-violet-200 sm:text-xl">{inviteCode}</code><Button onClick={() => { navigator.clipboard.writeText(inviteCode); toast.success("Código copiado."); }} size="icon" className="shrink-0 rounded-xl bg-white/[0.08] text-slate-200 hover:bg-white/[0.14]"><Copy className="h-4 w-4" /></Button></div><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Check className="h-3.5 w-3.5 text-emerald-300" /> Aguardando o segundo perfil aceitar o convite.</div></section></div>;
  return <div><SectionHeader eyebrow="NÓS DOIS" title="Construa uma visão financeira em conjunto." description="Mantenha seus dados privados por padrão e conecte um segundo perfil quando quiser enxergar planos, saldos e resultados a dois." /><div className="grid gap-5 lg:grid-cols-2"><form onSubmit={createSpace} className="rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/14 to-transparent p-6 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-400/15 text-violet-200"><HeartHandshake className="h-5 w-5" /></div><h2 className="mt-6 text-xl font-semibold text-white">Criar nosso espaço</h2><p className="mt-2 text-sm leading-6 text-slate-400">Gere um convite seguro para compartilhar com seu parceiro.</p><label className="mt-6 grid gap-2 text-xs font-medium text-slate-300">Nome do espaço<input value={name} onChange={event => setName(event.target.value)} className="atlas-input" placeholder="Ex.: Casa da Ana e João" /></label>{create.error && <p className="mt-3 text-sm text-rose-300">{create.error.message}</p>}<Button disabled={create.isPending} type="submit" className="mt-5 h-10 rounded-xl bg-violet-500 text-white hover:bg-violet-400">Criar convite</Button></form><form onSubmit={joinSpace} className="rounded-3xl border border-white/[0.08] bg-[#12131b] p-6 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/[0.06] text-slate-300"><UsersRound className="h-5 w-5" /></div><h2 className="mt-6 text-xl font-semibold text-white">Entrar em um espaço</h2><p className="mt-2 text-sm leading-6 text-slate-400">Use o código recebido para conectar seu perfil ao parceiro.</p><label className="mt-6 grid gap-2 text-xs font-medium text-slate-300">Código do convite<input value={code} onChange={event => setCode(event.target.value)} className="atlas-input uppercase tracking-[.12em]" placeholder="COLE O CÓDIGO" /></label>{join.error && <p className="mt-3 text-sm text-rose-300">{join.error.message}</p>}<Button disabled={join.isPending} type="submit" variant="outline" className="mt-5 h-10 rounded-xl border-white/10 bg-white/[0.025] text-slate-200 hover:bg-white/[0.08]">Conectar perfis</Button></form></div></div>;
}
